version: '2'
services:

  # Container MYSQL
    phalanx_db:
      image: mysql:5.7
      restart: always
      container_name: phalanx_db
      hostname: mysql
      environment:
#          MYSQL_ALLOW_EMPTY_PASSWORD: True
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: phalanx-development
      ports:
            - "3307:3306"

  # Container Redis
    phalanx_redisData:
      hostname: phalanx_redis_data
      container_name: phalanx_redis_data
      image: redis
      volumes:
            - /data
      command: echo

    phalanx_redis:
      hostname: phalanx_redis
      container_name: phalanx_redis
      image: redis
      ports:
            - "6379:6379"
      volumes_from:
            - phalanx_redisData

    # Container sidekiq
    sidekiq:
      hostname: phalanx_sidekiq
      container_name: phalanx_sidekiq
      build: .
      command: bundle exec sidekiq -c 25 -q default #zilean -q nunu -q chogath
      volumes:
            - .:/app
      depends_on:
            - phalanx_db
#      env_file: .env
      links:
            - phalanx_redis

    # App Phalanx
    web:
      hostname: phalanx_web
      container_name: phalanx_web
      build: .
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      volumes:
        - .:/app
#      env_file: .env
      ports:
        - "3001:3000"
      depends_on:
              - phalanx_db
      links:
              - phalanx_redis
              - phalanx_db
      environment:
              DB_USER: root
              DB_PASSWORD: password
              DB_NAME: phalanx-development
              DB_HOST: phalanx_db



#  # Container Intermediário para executar o comando do MYSQL
#    db_migrations:
#        hostname: db_migrations
#        container_name: db_migrations
#        build: .
##              context: .
##              dockerfile: ./Dockerfile
#        links:
#          - phalanx_db:phalanx_db
##        command:
##         - bash -c "bundle exec rails db:reset"
#        depends_on:
#          - phalanx_db


#docker-compose build
#docker-compose run --rm web rake db:reset
#docker-compose up
#docker-compose run --rm web rails g scaffold note title body:text
#docker-compose run --rm web rake db:reset