version: '2'
services:
  db:
    image: mysql:5.7
#   environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: phalanx-development
#      MYSQL_USER:  root
#      MYSQL_PASSWORD: password

    ports:
      - "3307:3306"
    volumes:
      - "db-data:/var/lib/mysql"

  redis:
    image: redis:3.2-alpine

  app: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #hostname: phalanx.com.br
    volumes:
      - .:/www/phalanx/app
    environment:
      REDIS_SIDEKIQ_URL: redis://redis:6379/0
      REDIS_CABLE_URL: redis://redis:6379/1
      DB_HOST: db
      DB_USER:  root
      DB_NAME: phalanx-development
      DB_PASSWORD: password
    ports:
      - "3001:3000"
    depends_on:
            - db
            - redis
    links:
            - redis
            - db

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - app

  ui:
      image: portainer/portainer
      restart: always
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
      expose:
        - 9000
      ports:
        - 3002:9000

volumes:
  db-data:
