version: '2'
services:

  # Container MYSQL
    phalanx_db:
      image: mysql:5.7
      restart: always
      container_name: phalanx_db
      hostname: mysql
      environment:
#          MYSQL_ALLOW_EMPTY_PASSWORD: True
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: phalanx-development
      ports:
            - "3307:3306"


   #Redis
    phalanx_redis:
      hostname: phalanx_redis
      container_name: phalanx_redis
      image: redis
      ports:
            - "6379:6379"
      volumes:
              - /data
      environment:
              REDIS_URL: phalanx_redis
              REDIS_PORT: 6359
#      command: export REDIS_URL=redis://127.0.0.1:6379/0


    # App Phalanx
    web:
      hostname: phalanx_web
      container_name: phalanx_web
      build: .
#      command: bundle exec rails db:reset && bundle exec rails s -p 3000 -b '0.0.0.0'
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      volumes:
        - .:/app
#      env_file: .env
      ports:
        - "3001:3000"
      depends_on:
              - phalanx_db
#              - phalanx_redis
      links:
#              - phalanx_redis
              - phalanx_db
      environment:
              DB_USER: root
              DB_PASSWORD: password
              DB_NAME: phalanx-development
              DB_HOST: phalanx_db
#              REDIS_URL: phalanx_redis
#              REDIS_HOST: 0.0.0.0
#              REDIS_PORT: 6379
#              REDIS_SIDEKIQ_URL: 172.20.0.4:6379/0
#              REDIS_CABLE_URL: 172.20.0.4:6379/1


    #Sidekiq
    sidekiq:
      hostname: phalanx_sidekiq
      container_name: phalanx_sidekiq
      build: .
      volumes:
            - .:/app
      depends_on:
            - phalanx_redis
#      env_file: .env
      links:
            - phalanx_redis
#      command: sidekiq -C config/sidekiq.yml
#      command: bundle exec sidekiq -c 25 -q default #zilean -q nunu -q chogath



#    worker:
#      <<: *app_base
#      command: bundle exec sidekiq
#      ports: []
#      depends_on:
#        - web

#  # Container Intermediário para executar o comando do MYSQL
#    db_migrations:
#        hostname: db_migrations
#        container_name: db_migrations
#        build: .
##              context: .
##              dockerfile: ./Dockerfile
#        links:
#          - phalanx_db:phalanx_db
##        command:
##         - bash -c "bundle exec rails db:reset"
#        depends_on:
#          - phalanx_db


#docker-compose build
#docker-compose run --rm web rake db:reset
#docker-compose up
#docker-compose run --rm web rails g scaffold note title body:text
#docker-compose run --rm web rake db:reset