version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phalanx-development
      MYSQL_USER:  root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      service1_net:
        ipv4_address: 172.22.0.101

  redis:
    image: redis:3.2-alpine
    restart: always
    networks:
      service1_net:
        ipv4_address: 172.22.0.102

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    environment:
     - NGINX_HOST=http://phalanx.net.br/
     - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  app: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/www/phalanx/app
    environment:
      REDIS_SIDEKIQ_URL: redis://redis:6379/0
      REDIS_CABLE_URL: redis://redis:6379/1
      DB_HOST: db
      DB_USER:  root
      DB_NAME: phalanx-development
      DB_PASSWORD: password
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    links:
      - redis
      - db
      - web

    networks:
      service1_net:
        ipv4_address: 172.22.0.100

  worker:
    <<: *app_base
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    restart: always
    depends_on:
      - app
  ui:
    image: portainer/portainer
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 3002:9000

volumes:
  db-data:

networks:
  service1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
