version: '2'
services:
  db:
    image: mysql:5.7
    ports:
          - "3307:3306"
    volumes:
      - "db-data:/var/lib/mysql"

  redis:
    image: redis:3.2-alpine

  app: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    environment:
      REDIS_SIDEKIQ_URL: redis://redis:6379/0
      REDIS_CABLE_URL: redis://redis:6379/1
      DB_HOST: db
      DB_USER:  root
      DB_NAME: phalanx-development
      DB_PASSWORD: password
    ports:
      - "3001:3000"
    depends_on:
            - db
            - redis
    links:
            - redis
            - db

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - app

volumes:
  db-data:

#docker-compose build
#docker-compose run --rm web rake db:reset
#docker-compose up
#docker-compose run --rm web rails g scaffold note title body:text
#docker-compose run --rm web rake db:reset

#bash -c 'while [ 0 ]; do docker ps -a;done';