SearchResult:
  fields:
    list: title, link, from, screenshot
    form: title, link, status, from, screenshot
    options:
      selectors: from
  options:
    export: csv
  search: title, link, status, from
  relationships: 
  application: Search
