---
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 10
qa:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - phalanx_default

REDIS_URL: <%= ENV['REDIS_URL'] %>
REDIS_PORT: <%= ENV['REDIS_PORT'] %>

#REDIS_HOST: 0.0.0.0
#REDIS_PORT: 6379
#REDIS_SIDEKIQ_URL: 0.0.0.0:
#REDIS_CABLE_URL: redis://redis:6379/1
