---
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 27
qa:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - phalanx_default

REDIS_URL: <%= ENV['REDIS_URL'] %>
REDIS_PORT: <%= ENV['REDIS_PORT'] %>
